name: Changelog

on:
  push:
    branches: ["master"]

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      # install and chache the toolchain
      - id: cache-rustup
        name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup
          key: toolchain-${{ matrix.os }}-${{ matrix.rust-version }}
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
      # Build and generate documentation (man docs are a step in the build of this tool)
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Generate HTML man documentation
        run: sudo apt install groff && groff -mandoc -Thtml docs/openapi-to-hurl.1 > docs/man.html
      # install and cache hyperfine
      - id: cache-hyperfine
        name: Cache hyperfine
        uses: actions/cache@v3
        with:
          path: /home/runner/.cargo/bin/hyperfine
          key: hyperfine-${{ matrix.os }}-${{ matrix.rust-version }}

      - if: ${{ steps.cache-hyperfine.outputs.cache-hit != 'true' }}
        name: Install hyperfine
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: hyperfine

      - name: Run conventional commits
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: "./Cargo.toml"
          version-path: "package.version"
          github-token: ${{ secrets.GH_TOKEN }}
          pre-changelog-generation: changelog/pre-changelog-gen.js

